serverAddr = "43.139.69.15"
  serverPort = 7000
  auth.method = "token"
  auth.token = "{frp_token}"

  [[proxies]]
  name = "intercom_backend"
  type = "tcp"
  localIP = "host.docker.internal"
  localPort = 20033
  remotePort = 20033

  [[proxies]]
  name = "pos_web_callback_test"
  type = "tcp"
  localIP = "host.docker.internal"
  localPort = 20034
  remotePort = 20034